# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    github_token: 9b0656cfc5c3dcf9aa081a6dc62a2895c737689a
    repos:
        - {org: ongr-io, repo: ElasticsearchDSL}
        - {org: ongr-io, repo: ElasticsearchBundle}

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
