# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    repos:
        - {org: ongr-io, repo: ElasticsearchBundle}
        - {org: ongr-io, repo: FilterManagerBundle}

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
