services:
    app.github.parser:
        class: AppBundle\Service\GithubParser
        calls:
            - [setGithubToken, [%github_token%]]

    app.bundle_tree_path.extension:
        class: AppBundle\Twig\BundleContentListExtension
        arguments: ["@es.manager.default.content"]
        tags:
            - { name: twig.extension }
